export const productData = [
    {
      id: 1,
      name: "Nike Air Max",
      category: "Tenis",
      price: 250,
      old_price: 300,
      descount: 20,
    },
    {
      id: 2,
      name: "Adidas Ultraboost",
      category: "Tenis",
      price: 300,
      old_price: 350,
      descount: 15,
    },
    {
      id: 3,
      name: "Puma RS-X",
      category: "Tenis",
      price: 200,
      old_price: null,
      descount: null,
    },
    {
      id: 4,
      name: "New Balance 990v5",
      category: "Tenis",
      price: 320,
      old_price: 400,
      descount: 20,
    },
    {
      id: 5,
      name: "Asics Gel-Kayano",
      category: "Tenis",
      price: 180,
      old_price: null,
      descount: null,
    },
    {
      id: 6,
      name: "Mizuno Wave Rider",
      category: "Tenis",
      price: 230,
      old_price: 270,
      descount: 15,
    },
    {
      id: 7,
      name: "Reebok Nano",
      category: "Tenis",
      price: 210,
      old_price: null,
      descount: null,
    },
    {
      id: 8,
      name: "Fila Disruptor",
      category: "Tenis",
      price: 150,
      old_price: 200,
      descount: 25,
    },
    {
      id: 9,
      name: "Converse All Star",
      category: "Tenis",
      price: 130,
      old_price: 180,
      descount: 10,
    },
    {
      id: 10,
      name: "Under Armour HOVR",
      category: "Tenis",
      price: 280,
      old_price: 330,
      descount: 15,
    },
  ];
  