export const productData = [
    {
      id: 1,
      name: "Nike Air Max",
      category: "Tenis",
      brand:"",
      model:"",
      price: 'R$ 250',
      old_price: 300,
      descount: 20,
      imagem: "",
    },
    {
      id: 2,
      name: "Nike Air Max",
      category: "Tenis",
      brand:"",
      model:"",
      price: 'R$ 250',
      old_price: 300,
      descount: 20,
      imagem: "",
    },
    {
      id: 3,
      name: "Nike Air Max",
      category: "Tenis",
      brand:"",
      model:"",
      price: 'R$ 250',
      old_price: 300,
      descount: 20,
      imagem: "",
    },
    {
      id: 4,
      name: "Nike Air Max",
      category: "Tenis",
      brand:"",
      model:"",
      price: 'R$ 250',
      old_price: 300,
      descount: 20,
      imagem: "",
    },
    {
      id: 5,
      name: "Nike Air Max",
      category: "Tenis",
      brand:"",
      model:"",
      price: 'R$ 250',
      old_price: 300,
      descount: 20,
      imagem: "",
    },
    {
      id: 6,
      name: "Nike Air Max",
      category: "Tenis",
      brand:"",
      model:"",
      price: 'R$ 250',
      old_price: 300,
      descount: 20,
      imagem: "",
    },
    {
      id: 7,
      name: "Nike Air Max",
      category: "Tenis",
      brand:"",
      model:"",
      price: 'R$ 250',
      old_price: 300,
      descount: 20,
      imagem: "",
    },
    {
      id: 8,
      name: "Nike Air Max",
      category: "Tenis",
      brand:"",
      model:"",
      price: 'R$ 250',
      old_price: 300,
      descount: 20,
      imagem: "",
    },
    {
      id: 9,
      name: "Nike Air Max",
      category: "Tenis",
      brand:"",
      model:"",
      price: 'R$ 250',
      old_price: 300,
      descount: 20,
      imagem: "",
    },
    {
      id: 10,
      name: "Nike Air Max",
      category: "Tenis",
      brand:"",
      model:"",
      price: 'R$ 250',
      old_price: 300,
      descount: 20,
      imagem: "",
    }
  ];
  